""""
visualizes the 3 sets /IN/OUT/Forgotten
"""
import torch
cn_model="cnmodels/CN_MODELSnum_epochs_100reg_lambda_4.0lr_0.01b1_Falsearch_ResNetdevice_cuda:0regularization_method_MASshared_head_Falseall_initialized_Falsebuffer_size_0batch_size_64lr_decay_rate_0.1dropr_0.0lr_scheduler_plt.pth"
cn_model="cnmodels/CN_MODELSnum_epochs_100reg_lambda_0.0lr_0.05b1_Falsearch_ResNetdevice_cuda:0regularization_method_MASshared_head_Trueall_initialized_Falseno_bias_Truebuffer_size_9000batch_size_16lr_decay_rate_0.9dropr_0.2lr_scheduler_exp.pth"
cn_model="cnmodels/CN_MODELSnum_epochs_100reg_lambda_0.0lr_0.0001b1_Falsearch_Alexdevice_cuda:0regularization_method_LwFshared_head_Falseall_initialized_Falseno_bias_Truebuffer_size_0batch_size_200lr_decay_rate_0.1dropr_0.0lr_scheduler_plt.pth"
cn_model="cnmodels/CN_MODELSnum_epochs_100reg_lambda_0.0lr_0.01b1_Falsearch_ResNetdevice_cuda:0regularization_method_LwFshared_head_Falseall_initialized_Falsebuffer_size_0batch_size_64lr_decay_rate_0.1dropr_0.0lr_scheduler_plt.pth"
cn_model="cnmodels/CN_MODELSnum_epochs_100reg_lambda_0.0lr_0.0001b1_Falsearch_Alexdevice_cuda:0regularization_method_LwFshared_head_Falseall_initialized_Falsebuffer_size_0batch_size_200lr_decay_rate_0.1dropr_0.0lr_scheduler_plt.pth"
cnmodels=torch.load(cn_model)
import NoveltyDetectionModules.In_out_visualizer
for i in range(len(cnmodels)):
    NoveltyDetectionModules.In_out_visualizer.visulaize_cnmodel(cnmodels[i],"tsne_fig/ResNet_LwF_"+str(i),"cuda:0")
